@baseUrl = http://localhost:3000

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "user@example.com",
    "password": "password",
    "chave-malvada": "valor-malvado"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/456

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "Luis Henrique",
  "email": "user1@email.com",
  "password": "123456"
}
