@baseUrl = http://localhost:3000

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "user@example.com",
    "password": "password"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/456