@baseUrl = http://localhost:3000
@jwtToken = {{authLogin.response.body.accessToken}}

@userNameForTesting = Luis Henrique
@userEmailForTesting = luishenrisc1@gmail.com
@userPasswordForTesting = 123456
@userNewPasswordForTesting = 123456

# AUTH ########################################################################

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

# USER ########################################################################

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}",
  "password": "{{userPasswordForTesting}}"
}

### Update user
# @name updateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "{{userNameForTesting}}",
  "email": "{{userEmailForTesting}}"
}

### Update user password
# @name updateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "{{userPasswordForTesting}}",
  "newPassword": "{{userNewPasswordForTesting}}"
}

### Read logged user
# @name readOneUser
GET {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}

### Read user by ID
# @name readUserById
GET {{baseUrl}}/user/456
Authorization: Bearer {{jwtToken}}

### Delete logged user
# @name deleteOneUser
DELETE {{baseUrl}}/user/me
Authorization: Bearer {{jwtToken}}
